agent:
  name: "AI Testing Agent"
  version: "1.0.0"
  max_iterations: 10
  timeout: 30

llm:
  provider: "openai"  # openai or anthropic
  model: "gpt-4"
  temperature: 0.3
  max_tokens: 2000

browser:
  type: "chromium"  # chromium, firefox, webkit
  headless: true
  viewport:
    width: 1920
    height: 1080
  timeout: 60000

testing:
  visual_regression:
    enabled: true
    threshold: 0.95
    pixel_diff_threshold: 0.1
  api_testing:
    enabled: true
    timeout: 10
  load_testing:
    enabled: true
    users: 10
    spawn_rate: 2
    duration: 60

output:
  screenshots_dir: "./screenshots"
  reports_dir: "./reports"
  tests_dir: "./generated_tests"
  
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"